name: next-prisma-test
services:
  # app:
  #   build: .
  #   image: nextjs-dev
  #   container_name: next-prisma-nextjs
  #   ports:
  #    - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
  
  postgres:
    image: postgres:15-alpine
    container_name: next-prisma-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    # volumes:
    #   - postgres_next_data:/var/lib/postgresql/data
